### PR TITLE
Update IP addresses and add network group parameter in PTB fhicl. Set default fhicl path to local.

### PR DESCRIPTION
**Pull request by jsensenig**
There are 3 changes,
* Updated PTB configuration IP addresses and added a parameter for network group. 
* Updated the firmware configuration also in `ptb01.fcl`.
* Change `sbn-nd` fhicl search path default to local configs.

### CODE REVIEW

**Review by kalradaisy — COMMENTED** [review]
Could you please take a run with all these changes and post a run number?

**Comment by jsensenig** [comment]
This code was tested successfully,
* Location: ND
* Run: 1393
* Components: tpc01, tpc02, ptb01

**Comment by kalradaisy** [comment]
Thanks, Jon. I am fine with the changes made to the code.

**Comment by jsensenig** [comment]
@gennadiy-fnal this PR along with an associated one in `sbndaq_artdaq` has been reviewed by Bill and Daisy so I would like to request it to be merged into the `develop` branch. Thank you!

**Review by wbadgett — APPROVED** [review]
Looks good

**Pull request merged**
